FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm64v8 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm64v8
WORKDIR /app
COPY --from=build-env /app/out ./

# We need privileged access, so don't add moduleuser!
# RUN useradd -ms /bin/bash moduleuser
# USER moduleuser

ENTRYPOINT ["dotnet", "IoTEdgeSmagribotArduinoSerial.dll"]